//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_shop
    {
        public int PCID { get; set; }
        public string CPU { get; set; }
        public string GPU { get; set; }
        public string RAM { get; set; }
        public string Storage { get; set; }
        public Nullable<bool> Storage_type { get; set; }
        public string ImageUrl { get; set; }
        public string Price { get; set; }
    
        public virtual Cart_PC Cart_PC { get; set; }
    }
}
